Fix issue while dealing with prefixed Index.
jolicode/elastically pull request #40
Opened 2020-10-13 10:39 UTC by atapatel

Fix issue while dealing with prefixed Index. When i try to use prefix index for elastic search purge of indexing is not working. It is taking two time prefixing index name while closing and deleting indexes.

2020-10-13 10:42 UTC, damienalexandre commented
Are you calling purgeOldIndices with the real index name? (without the prefix I mean).

2020-10-13 10:49 UTC, atapatel commented
@damienalexandre  Yes, i am using this library along with this library https://github.com/monsieurbiz/SyliusSearchPlugin.

2020-10-13 11:27 UTC, atapatel commented
@damienalexandre Am I doing something wrong here?

2020-10-13 11:36 UTC, damienalexandre commented
Yes this change looks strange to me, and the tests are red: https://travis-ci.org/github/jolicode/elastically/jobs/735342582#L448

The purgeOldIndices function should not care about the prefix option because it fetch the real concrete name from the State API. The test show how it's supposed to be used:

https://github.com/jolicode/elastically/blob/223752b125f17e7ccb8563adc0657c1eccfa3a94/tests/IndexBuilderTest.php#L134-L172

Here, "hop" is my index name, which is used as an alias in Elasticsearch. The concrete index name will be something like "PREFIX_INDEXNAME_DATE". We need to add a test with a prefix configured to check the behavior. Could you try? (running the tests is done via `make test`.

_Also, the CS is broken, can you run `make cs`?_

2020-10-13 18:13 UTC, atapatel commented
@damienalexandre Do you want me to create test cases for this scenario?

2020-10-13 18:19 UTC, damienalexandre commented
Yes that would be great, or wait until end of the week, I will have some time to look into this issue as well.

Thank you!

2020-10-15 15:14 UTC, damienalexandre requested changes
Hello!
I just added a test for this here: https://github.com/jolicode/elastically/commit/2a67fcee93fab0d78226b3d4778d869280c8b2ae

You were right there is a bug when using the purge method with prefixed indices.

I suggest to change the code that effectively delete and closes the indexes to avoid any "name" manipulation. As we have the real index name, but can't use $client->getIndex(), creating the Elastica Index object ourself is the better way to access it for real.

What do you think?

2020-10-15 15:14 UTC, damienalexandre commented on src/IndexBuilder.php
> +                $this->client->getIndex($this->client->getPureIndexName($realIndexName))->delete();
```suggestion
                $index = new Index($this->client, $realIndexName);
                $index->delete();
```

2020-10-15 15:14 UTC, damienalexandre commented on src/IndexBuilder.php
> +                $this->client->getIndex($this->client->getPureIndexName($realIndexName))->close();
```suggestion
                $index = new Index($this->client, $realIndexName);
                $index->close();
```

2020-10-16 05:17 UTC, atapatel commented on src/IndexBuilder.php
> +                $this->client->getIndex($this->client->getPureIndexName($realIndexName))->delete();
This looks good :)

2020-10-16 05:18 UTC, atapatel commented on src/IndexBuilder.php
> +                $this->client->getIndex($this->client->getPureIndexName($realIndexName))->close();
:+1:

2020-10-16 05:19 UTC, atapatel commented
I will update the code according to your suggestion and push code here. :) . Thanks a lot, @damienalexandre . You have created a really nice library.

2020-10-16 05:46 UTC, atapatel commented
@damienalexandre Just one suggestion can you label this pull request as `Hacktoberfest` and `good first issue` ?

2020-10-16 06:53 UTC, merged

2020-10-16 06:53 UTC, damienalexandre commented
All done, thanks!